-- CREATE TABLE  travel (
--                 id INTEGER PRIMARY KEY AUTOINCREMENT,
--                 name TEXT NOT NULL,
--                 mobile TEXT NOT NULL UNIQUE,
--                 boarding TEXT NOT NULL,
--                 destination TEXT NOT NULL,
--                 email TEXT NOT NULL UNIQUE,
--                 date TEXT NOT NULL 
--             );